-- Enable pgvector extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Atomic Insights Table
-- Stores the granular "ideas" extracted from videos
CREATE TABLE IF NOT EXISTS insight_atoms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id TEXT NOT NULL, -- References podcasts(id) but loosely to allow flexibility
    segment_index INTEGER, -- Which segment does this belong to
    
    -- The Core Content
    topic TEXT NOT NULL,
    entity TEXT,
    claim TEXT NOT NULL,
    stance TEXT CHECK (stance IN ('Optimistic', 'Pessimistic', 'Neutral', 'Critical', 'Supportive')),
    certainty TEXT CHECK (certainty IN ('High', 'Medium', 'Low')),
    quote TEXT,
    
    -- Timing
    start_time NUMERIC,
    end_time NUMERIC,
    
    -- The Semantic Fingerprint (1536 dimensions for text-embedding-3-small)
    embedding vector(1536),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create an index for fast similarity search
CREATE INDEX ON insight_atoms USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);


-- 2. Atom Links Table
-- Stores the relationships between atoms (The "Web")
CREATE TABLE IF NOT EXISTS atom_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    atom_a_id UUID REFERENCES insight_atoms(id) ON DELETE CASCADE,
    atom_b_id UUID REFERENCES insight_atoms(id) ON DELETE CASCADE,
    
    relationship_type TEXT CHECK (relationship_type IN ('CORROBORATION', 'CONTRADICTION', 'EXTENSION', 'PREDICTION_CHECK', 'RELATED')),
    confidence NUMERIC, -- 0.0 to 1.0
    explanation TEXT, -- Why are they linked? (Generated by LLM)
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Ensure we don't link an atom to itself or duplicate links
    CONSTRAINT no_self_link CHECK (atom_a_id != atom_b_id),
    UNIQUE(atom_a_id, atom_b_id)
);


-- 3. Meta Narratives Table
-- Stores the synthesized stories generated from clusters of atoms
CREATE TABLE IF NOT EXISTS meta_narratives (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    title TEXT NOT NULL,
    summary TEXT,
    content TEXT NOT NULL, -- The full generated article/insight
    
    -- Metadata
    primary_topic TEXT,
    atom_ids UUID[], -- Array of atom IDs used to generate this
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

